/**
 * PDF touch handling, on a fixture that actually exists.
 *
 * Every board PDF in this project is proprietary and gitignored, so the PDF
 * specs all skipped on a clean checkout — which is how a tablet could reach
 * "almost unusable" with a full green suite. `tests/fixtures/two-page-text.pdf`
 * is generated by the script beside it and has no such problem.
 *
 * The three failures under test are all state-tracking, not geometry:
 *  - a pointer that never gets its `pointerup` (iOS takes capture back when the
 *    system interrupts) leaves the touch map at two entries, and every later
 *    move takes the pinch branch — panning is simply dead until the tab is
 *    reopened;
 *  - a third finger resting on the glass used to match neither branch;
 *  - a tap did nothing at all on touch, so the viewer's one real interaction
 *    was unreachable on a tablet.
 */
import { test, expect, type Page } from '@playwright/test';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const PDF = path.resolve(here, 'fixtures/two-page-text.pdf');
/** 16 pages, because a paging bug cannot show itself inside a document whose
 *  every page is already in the rendered window. Both fixtures come from
 *  fixtures/make-test-pdf.mjs. */
const LONG_PDF = path.resolve(here, 'fixtures/many-page-text.pdf');

type Pt = { x: number; y: number };

async function openPdf(page: Page): Promise<{ box: Pt & { w: number; h: number } }> {
  await page.goto('/');
  await expect(page.getByTestId('toolbar')).toBeVisible({ timeout: 20000 });
  await page.getByTestId('file-input').setInputFiles(PDF);
  const container = page.locator('.pdf-canvas-container');
  await expect(container).toBeVisible({ timeout: 20000 });
  await expect(page.locator('.pdf-page-wrapper canvas').first()).toBeVisible({ timeout: 20000 });
  await page.waitForTimeout(1500);
  const b = (await container.boundingBox())!;
  return { box: { x: b.x, y: b.y, w: b.width, h: b.height } };
}

/** The wrapper's CSS transform carries pan and zoom; reading it is how a test
 *  sees what a gesture did without reaching into component refs. */
async function transform(page: Page): Promise<string> {
  return page.evaluate(() =>
    (document.querySelector('.pdf-page-wrapper') as HTMLElement | null)?.style.transform ?? '');
}

/** Parsed form, because the engines do not agree on the serialisation:
 *  Chromium writes `translate(0px, 0px)`, WebKit drops the zero y and writes
 *  `translate(0px)`. Comparing numbers is the only portable way. */
async function view(page: Page): Promise<{ x: number; y: number; scale: number }> {
  const t = await transform(page);
  const tr = /translate\(([-\d.]+)px(?:,\s*([-\d.]+)px)?\)/.exec(t);
  const sc = /scale\(([-\d.]+)\)/.exec(t);
  return { x: Number(tr?.[1] ?? 0), y: Number(tr?.[2] ?? 0), scale: Number(sc?.[1] ?? 1) };
}

/** Synthetic pointers, dispatched at the touch surface — the one element every
 *  real pointer event targets. Playwright can inject one touch at most, and
 *  these cases are all about what happens with two or three — or with one that
 *  never reports its release. */
async function pointer(page: Page, type: string, id: number, p: Pt, kind = 'touch') {
  await page.evaluate(({ type, id, p, kind }) => {
    const el = document.querySelector('.pdf-touch-surface')!;
    el.dispatchEvent(new PointerEvent(type, {
      pointerId: id, pointerType: kind, isPrimary: id === 1,
      clientX: p.x, clientY: p.y, button: 0, buttons: type === 'pointerup' ? 0 : 1,
      bubbles: true, cancelable: true,
    }));
  }, { type, id, p, kind });
}

test.describe('PDF touch', () => {
  /** Scrolling with a finger must turn pages, the way scrolling with a wheel
   *  does. The flip lived only in the wheel handler, so a finger panned past
   *  the bottom of the current page for ever: the pan kept growing, the page
   *  indicator never moved, and since only `currentPage ± 1` is rendered,
   *  everything past the neighbour was blank paper. Measured before the fix —
   *  fourteen swipes, pan at −11648 px, page still 1.
   *
   *  The ink check is the point. Asserting the page number alone would have
   *  passed on a viewer showing a white rectangle with the right label.
   */
  test('swiping through a long document keeps turning pages and never goes blank',
    async ({ page }) => {
      await page.goto('/');
      await expect(page.getByTestId('toolbar')).toBeVisible({ timeout: 20000 });
      await page.getByTestId('file-input').setInputFiles(LONG_PDF);
      await expect(page.locator('.pdf-canvas-container')).toBeVisible({ timeout: 20000 });
      await expect(page.locator('.pdf-page-wrapper canvas').first()).toBeVisible({ timeout: 20000 });
      await page.waitForTimeout(1500);

      const b = (await page.locator('.pdf-canvas-container').boundingBox())!;
      const from = { x: b.x + b.width / 2, y: b.y + b.height * 0.75 };
      const distance = b.height * 0.8;

      /** Fraction of the rendered page that is not white. Blank paper is 0. */
      const ink = () => page.evaluate(() => {
        const w = document.querySelector('.pdf-page-wrapper');
        const main = w ? [...w.children].find(e => e.tagName === 'CANVAS' && !e.className) : null;
        if (!(main instanceof HTMLCanvasElement) || !main.width) return -1;
        const c = document.createElement('canvas');
        c.width = 60; c.height = 60;
        const g = c.getContext('2d')!;
        g.drawImage(main, 0, 0, 60, 60);
        const d = g.getImageData(0, 0, 60, 60).data;
        let dark = 0;
        for (let i = 0; i < d.length; i += 4) if (d[i] < 200) dark++;
        return dark / 3600;
      });
      const pageNo = () => page.locator('.pdf-page-input').first().inputValue();

      expect(await pageNo()).toBe('1');
      expect(await ink(), 'page 1 should have text on it').toBeGreaterThan(0);

      for (let swipe = 1; swipe <= 10; swipe++) {
        await pointer(page, 'pointerdown', 1, from);
        for (let i = 1; i <= 16; i++) {
          await pointer(page, 'pointermove', 1, { x: from.x, y: from.y - (distance * i) / 16 });
        }
        await pointer(page, 'pointerup', 1, { x: from.x, y: from.y - distance });
        await page.waitForTimeout(500);
        expect(await ink(), `blank page after swipe ${swipe}`).toBeGreaterThan(0);
      }

      // Past page 2 is the meaningful line, and it does not depend on the
      // viewport: a stuck counter sits at 1, and 1 ± 1 is the whole set of
      // pages such a viewer can draw. How much further ten swipes get depends
      // on how tall the panel is, so asserting a specific page would only make
      // this brittle.
      expect(Number(await pageNo()), 'the page counter should have advanced').toBeGreaterThan(2);
    });


  test('a pointer whose capture is lost does not wedge the viewer into a permanent pinch', async ({ page }) => {
    const { box } = await openPdf(page);
    const a = { x: box.x + box.w * 0.4, y: box.y + box.h * 0.5 };
    const b = { x: box.x + box.w * 0.6, y: box.y + box.h * 0.5 };

    // Two fingers down, then the system takes the capture — no pointerup ever
    // arrives for either.
    await pointer(page, 'pointerdown', 1, a);
    await pointer(page, 'pointerdown', 2, b);
    await page.evaluate(() => {
      const el = document.querySelector('.pdf-touch-surface')!;
      for (const id of [1, 2]) {
        el.dispatchEvent(new PointerEvent('lostpointercapture', {
          pointerId: id, pointerType: 'touch', bubbles: true,
        }));
      }
    });

    // A single finger must now pan again.
    const before = await transform(page);
    await pointer(page, 'pointerdown', 1, a);
    for (let i = 1; i <= 6; i++) {
      await pointer(page, 'pointermove', 1, { x: a.x, y: a.y - i * 15 });
    }
    await pointer(page, 'pointerup', 1, { x: a.x, y: a.y - 90 });
    await page.waitForTimeout(300);
    expect(await transform(page)).not.toBe(before);
  });

  test('a third finger resting on the glass does not freeze the page', async ({ page }) => {
    const { box } = await openPdf(page);
    const c = { x: box.x + box.w / 2, y: box.y + box.h / 2 };

    await pointer(page, 'pointerdown', 1, { x: c.x - 40, y: c.y });
    await pointer(page, 'pointerdown', 2, { x: c.x + 40, y: c.y });
    await pointer(page, 'pointerdown', 3, { x: c.x, y: c.y + 120 });   // resting thumb
    const before = await transform(page);
    for (let i = 1; i <= 6; i++) {
      await pointer(page, 'pointermove', 1, { x: c.x - 40 - i * 10, y: c.y });
      await pointer(page, 'pointermove', 2, { x: c.x + 40 + i * 10, y: c.y });
    }
    await page.waitForTimeout(200);
    expect(await transform(page)).not.toBe(before);
  });

  /** A pinch must leave the content under the fingers where it was.
   *
   *  Two mistakes hid behind the same symmetric test. The midpoint was frozen
   *  at the second pointerdown, which holds only while the two fingers'
   *  movements cancel exactly — mid = (f1 + f2) / 2 is constant iff
   *  Δf1 = -Δf2. That is a knife edge: whenever one finger moves further or
   *  faster than the other, or the hand drifts, the midpoint moves with it and
   *  the anchor goes stale by half the difference. And once the midpoint
   *  tracked, anchoring the scale on the *new* midpoint double-counted its
   *  travel by (1 - ratio) per event, leaving 24 px of drift across one
   *  gesture. Both fingers stay put exactly when
   *  pan₁ = mid₀ - ratio·(mid₀ - pan₀) + (mid₁ - mid₀).
   *
   *  The test parks one finger because that is the *largest* midpoint drift
   *  for a given spread, not because it is the typical gesture — it puts the
   *  error where a 2 px tolerance can see it. A perfectly symmetric pinch is
   *  the one case a frozen midpoint survives, which is how this went unnoticed.
   */
  test('a pinch keeps the content under the fingers, however they move', async ({ page }) => {
    const { box } = await openPdf(page);
    expect(await view(page)).toEqual({ x: 0, y: 0, scale: 1 });

    const anchorPt = { x: box.x + box.w * 0.35, y: box.y + box.h * 0.45 };
    const other = { x: box.x + box.w * 0.65, y: box.y + box.h * 0.45 };

    // The page point currently under the finger that will not move.
    const v0 = await view(page);
    const pagePt = {
      x: (anchorPt.x - box.x - v0.x) / v0.scale,
      y: (anchorPt.y - box.y - v0.y) / v0.scale,
    };

    await pointer(page, 'pointerdown', 1, anchorPt);
    await pointer(page, 'pointerdown', 2, other);
    for (let i = 1; i <= 16; i++) {
      await pointer(page, 'pointermove', 2, { x: other.x + i * 12, y: other.y });
    }
    await page.waitForTimeout(80);

    const v1 = await view(page);
    expect(v1.scale, 'the pinch should have zoomed in').toBeGreaterThan(1.5);
    const onScreen = box.x + v1.x + pagePt.x * v1.scale;
    expect(Math.abs(onScreen - anchorPt.x),
      `content drifted ${(onScreen - anchorPt.x).toFixed(1)}px from a stationary finger`)
      .toBeLessThan(2);

    await pointer(page, 'pointerup', 1, anchorPt);
    await pointer(page, 'pointerup', 2, { x: other.x + 192, y: other.y });
  });

  /** Every touch must land on the same element, wherever the finger is.
   *
   *  On the iPad a drag or pinch that started over page 1 worked and one that
   *  started over page 2 did nothing, and the only difference between them
   *  was the touch target: page 1 is the main <canvas>, page 2 is a
   *  `pointer-events: none` neighbour that fell through to the container — an
   *  `overflow: hidden` scroll container carrying the UI-scale `zoom`. In
   *  tiled mode the main canvas is `visibility: hidden`, so there everything
   *  fell through. Chromium treats the two targets alike, which is why no
   *  fixture ever showed it; this pins the invariant instead, so the
   *  asymmetry cannot come back.
   */
  test('a touch anywhere in the panel targets the touch surface', async ({ page }) => {
    await page.goto('/');
    await expect(page.getByTestId('toolbar')).toBeVisible({ timeout: 20000 });
    await page.getByTestId('file-input').setInputFiles(LONG_PDF);
    await expect(page.locator('.pdf-page-wrapper canvas').first()).toBeVisible({ timeout: 20000 });
    await page.waitForTimeout(1200);

    const b = (await page.locator('.pdf-canvas-container').boundingBox())!;
    const targets = await page.evaluate(({ x, ys }) =>
      ys.map(y => document.elementFromPoint(x, y)?.className ?? null),
      { x: b.x + b.width / 2, ys: [b.y + 100, b.y + b.height * 0.5, b.y + b.height * 0.95] });
    // Top of page 1, somewhere in the middle, and down where page 2 (or blank
    // paper below a short page) sits: one target for all of them.
    for (const t of targets) expect(t).toBe('pdf-touch-surface');
  });

  /** The same scenario driven by the browser's own hit-testing, since the
   *  synthetic pointers elsewhere in this file choose their target for it. */
  test('real touches over page 2 pan and zoom like touches over page 1', async ({ page, browserName }) => {
    test.skip(browserName !== 'chromium', 'multi-touch injection is CDP, Chromium only');
    await page.goto('/');
    await expect(page.getByTestId('toolbar')).toBeVisible({ timeout: 20000 });
    await page.getByTestId('file-input').setInputFiles(LONG_PDF);
    await expect(page.locator('.pdf-page-wrapper canvas').first()).toBeVisible({ timeout: 20000 });
    await page.waitForTimeout(1200);

    const cdp = await page.context().newCDPSession(page);
    const touch = (type: string, pts: Pt[]) => cdp.send('Input.dispatchTouchEvent', {
      type, touchPoints: pts.map((q, i) => ({ x: q.x, y: q.y, id: i })),
    });
    const b = (await page.locator('.pdf-canvas-container').boundingBox())!;
    // Page 1 is fitted to width; page 2 begins one page-height down. Aim well
    // below the first page for the second point.
    const onPage2 = { x: b.x + b.width / 2, y: b.y + b.height * 0.9 };

    const y0 = (await view(page)).y;
    await touch('touchStart', [onPage2]);
    for (let i = 1; i <= 10; i++) await touch('touchMove', [{ x: onPage2.x, y: onPage2.y - i * 15 }]);
    await touch('touchEnd', []);
    await page.waitForTimeout(600);
    expect((await view(page)).y, 'a drag that starts over page 2 should pan').not.toBe(y0);

    const zoomBefore = await page.locator('.pdf-zoom-info').first().textContent();
    await touch('touchStart', [{ x: onPage2.x - 40, y: onPage2.y }]);
    await touch('touchStart', [{ x: onPage2.x - 40, y: onPage2.y }, { x: onPage2.x + 40, y: onPage2.y }]);
    for (let i = 1; i <= 10; i++) {
      const d = 40 + i * 8;
      await touch('touchMove', [{ x: onPage2.x - d, y: onPage2.y }, { x: onPage2.x + d, y: onPage2.y }]);
    }
    await touch('touchEnd', [{ x: onPage2.x - 120, y: onPage2.y }]);
    await touch('touchEnd', []);
    await page.waitForTimeout(800);
    expect(await page.locator('.pdf-zoom-info').first().textContent(),
      'a pinch over page 2 should zoom').not.toBe(zoomBefore);
  });

  /** A flick has to carry after the finger lifts.
   *
   *  Inertia had never run once, on any platform: the loop decayed
   *  `velocityRef` while `velocityRef.current = {x:0,y:0}` ran synchronously
   *  below it, before the first `requestAnimationFrame` callback could fire —
   *  so the first frame always failed the `< 0.2` test and returned. With a
   *  mouse nobody notices, because releasing a drag is *meant* to stop dead;
   *  on a touch screen a flick that goes nowhere is most of what "scrolling is
   *  broken" means. And once it does carry, it has to turn pages like any
   *  other scroll, or it glides past the next boundary onto blank paper.
   *
   *  The assertion is that the page advances *after the finger is up* —
   *  checking ink alone passes against a dead inertia, since the drag itself
   *  already flips correctly.
   */
  test('a flick carries after the finger lifts, and keeps turning pages', async ({ page }) => {
    await page.goto('/');
    await expect(page.getByTestId('toolbar')).toBeVisible({ timeout: 20000 });
    await page.getByTestId('file-input').setInputFiles(LONG_PDF);
    await expect(page.locator('.pdf-page-wrapper canvas').first()).toBeVisible({ timeout: 20000 });
    await page.waitForTimeout(1500);

    const b = (await page.locator('.pdf-canvas-container').boundingBox())!;
    const from = { x: b.x + b.width / 2, y: b.y + b.height * 0.8 };

    const ink = () => page.evaluate(() => {
      const w = document.querySelector('.pdf-page-wrapper');
      const main = w ? [...w.children].find(e => e.tagName === 'CANVAS' && !e.className) : null;
      if (!(main instanceof HTMLCanvasElement) || !main.width) return -1;
      const c = document.createElement('canvas');
      c.width = 60; c.height = 60;
      const g = c.getContext('2d')!;
      g.drawImage(main, 0, 0, 60, 60);
      const d = g.getImageData(0, 0, 60, 60).data;
      let dark = 0;
      for (let i = 0; i < d.length; i += 4) if (d[i] < 200) dark++;
      return dark / 3600;
    });

    const pageNo = async () => Number(await page.locator('.pdf-page-input').first().inputValue());

    await pointer(page, 'pointerdown', 1, from);
    for (let i = 1; i <= 6; i++) {
      await pointer(page, 'pointermove', 1, { x: from.x, y: from.y - i * 60 });
    }
    await pointer(page, 'pointerup', 1, { x: from.x, y: from.y - 360 });

    const atLift = await pageNo();
    await page.waitForTimeout(1800);        // let the deceleration run out
    const settled = await pageNo();

    expect(settled, 'the flick should carry past where the finger let go')
      .toBeGreaterThan(atLift);
    expect(await ink(), 'the page the flick settled on should be drawn')
      .toBeGreaterThan(0);
  });

  /** The iPadOS shape, and the one neither stream can handle alone.
   *
   *  A two-finger pinch there arrives as BOTH a pointer stream and WebKit's
   *  `gesture*` stream, and when the engine claims the gesture for its own
   *  recogniser the second finger's `pointerdown` may never be dispatched. So
   *  `activeTouchesRef.size` stays 1: the gesture path zoomed about the
   *  two-finger midpoint while the single-finger drag path panned along finger
   *  one, from the same gesture, on interleaved events. Exactly one stream may
   *  own a gesture, and the hand-off has to be explicit in both directions —
   *  it used to exist in one.
   *
   *  `gesturestart` is dispatched as a MouseEvent carrying a `scale`: a real
   *  GestureEvent cannot be synthesised (see touch-webkit.webkit.spec.ts), and
   *  the handlers read only `type`, `clientX/Y` and `scale`.
   */
  test('a gesture claimed while one finger is registered does not also drag', async ({ page }) => {
    const { box } = await openPdf(page);
    const at = { x: box.x + box.w * 0.5, y: box.y + box.h * 0.5 };

    const gesture = (type: string, scale: number, p: { x: number; y: number }) =>
      page.evaluate(({ type, scale, p }) => {
        const el = document.querySelector('.pdf-touch-surface')!;
        const e = new MouseEvent(type, { clientX: p.x, clientY: p.y, bubbles: true, cancelable: true });
        Object.defineProperty(e, 'scale', { value: scale });
        Object.defineProperty(e, 'rotation', { value: 0 });
        el.dispatchEvent(e);
      }, { type, scale, p });

    // One finger registers; the engine then claims the gesture.
    await pointer(page, 'pointerdown', 1, at);
    await gesture('gesturestart', 1, at);

    const before = await view(page);

    // The registered finger keeps moving — as it does in a real pinch — while
    // the gesture reports a scale. Only the zoom may result.
    for (let i = 1; i <= 10; i++) {
      await pointer(page, 'pointermove', 1, { x: at.x, y: at.y - i * 12 });
      await gesture('gesturechange', 1 + i * 0.15, at);
    }
    await page.waitForTimeout(80);

    const during = await view(page);
    expect(during.scale, 'the gesture should have zoomed').toBeGreaterThan(1.5);

    // The anchor is the gesture midpoint, which never moved here, so the page
    // point under it must not move either. If the drag path had also run, the
    // pan would carry the finger's 120 px of travel on top.
    const pagePt = { x: (at.x - box.x - before.x) / before.scale, y: (at.y - box.y - before.y) / before.scale };
    const nowY = box.y + during.y + pagePt.y * during.scale;
    expect(Math.abs(nowY - at.y),
      `content drifted ${(nowY - at.y).toFixed(1)}px from a stationary anchor`).toBeLessThan(3);

    // …and once the gesture ends, the finger that is still down scrolls again.
    await gesture('gestureend', 1 + 10 * 0.15, at);
    await page.waitForTimeout(50);
    const beforePan = await view(page);
    for (let i = 1; i <= 8; i++) {
      await pointer(page, 'pointermove', 1, { x: at.x, y: at.y - 120 - i * 12 });
    }
    await page.waitForTimeout(80);
    expect((await view(page)).y, 'a finger still down after a pinch should scroll')
      .not.toBe(beforePan.y);
    await pointer(page, 'pointerup', 1, { x: at.x, y: at.y - 216 });
  });

  test('a tap looks up the word under it — on a finger, not only a mouse', async ({ page }) => {
    const { box } = await openPdf(page);
    const devHooks = await page.evaluate(
      () => '__pdfStore' in (window as unknown as Record<string, unknown>));
    test.skip(!devHooks, 'pdf store is a DEV-only global');

    // Aim in the fixture's own PDF coordinates so the target does not depend on
    // the panel size: the page opens fitted to width at zoom 1 / pan 0, its
    // wrapper sits at the container origin, and the media box is 595×842. Line
    // one is 18 pt text with its baseline at y=740 starting at x=60, so PDF
    // (120, ~746) is inside it. The small vertical sweep absorbs the ascent.
    expect(await view(page)).toEqual({ x: 0, y: 0, scale: 1 });
    const s = box.w / 595;
    const word = async () => page.evaluate(() =>
      (window as unknown as { __pdfStore: { lastClickedWord: string | null } })
        .__pdfStore.lastClickedWord);
    expect(await word()).toBeNull();

    for (let dy = 0; dy <= 14 && !(await word()); dy += 2) {
      const p = { x: box.x + 120 * s, y: box.y + (842 - 750 + dy) * s };
      await pointer(page, 'pointerdown', 1, p);
      await pointer(page, 'pointerup', 1, p);
      await page.waitForTimeout(80);
    }
    expect(await word()).toBeTruthy();
  });

  test('a touch drag pans and does not also count as a tap', async ({ page }) => {
    const { box } = await openPdf(page);
    const devHooks = await page.evaluate(
      () => '__pdfStore' in (window as unknown as Record<string, unknown>));
    test.skip(!devHooks, 'pdf store is a DEV-only global');

    const start = { x: box.x + box.w * 0.35, y: box.y + box.h * 0.6 };
    const before = await transform(page);
    await pointer(page, 'pointerdown', 1, start);
    for (let i = 1; i <= 6; i++) {
      await pointer(page, 'pointermove', 1, { x: start.x, y: start.y - i * 15 });
    }
    await pointer(page, 'pointerup', 1, { x: start.x, y: start.y - 90 });
    await page.waitForTimeout(300);

    expect(await transform(page)).not.toBe(before);
    // The whole reason touch taps were disabled: a drag that also fired the
    // lookup. `wasDrag` is what makes enabling them safe.
    expect(await page.evaluate(() =>
      (window as unknown as { __pdfStore: { lastClickedWord: string | null } })
        .__pdfStore.lastClickedWord)).toBeNull();
  });
});
